@BooksAPI_HostAddress = http://localhost:5172

###
GET {{BooksAPI_HostAddress}}/api/books
Accept: application/json

###
GET {{BooksAPI_HostAddress}}/api/books/1
Accept: application/json


###
POST {{BooksAPI_HostAddress}}/api/books
Content-Type: application/json
{
    "title": "New Book Title",
    "author": "New Author",
    "yearPublished": "2024"
}

###
PUT {{BooksAPI_HostAddress}}/api/books/1
Content-Type: application/json
{
    "title": "Updated Book Title",
    "author": "Updated Author",
    "yearPublished": "2025"
}


###
DELETE {{BooksAPI_HostAddress}}/api/books/1